// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqbrlcpidilslnqsizsn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxYnJsY3BpZGlsc2xucXNpenNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MTM4MTIsImV4cCI6MjA2MzQ4OTgxMn0.eNJ13LHhaX9-XKRh70QhoQh_bn5VezdIA5T-YdldD_4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);